### ISSUE TITLE
fido must bind to window.navigator

### ISSUE THREAD

**Issue by herrjemand** [apowers313/cordova-fido#6]
In my pull request #1 I have patched fido command to protocol specification. However these command need to be part of `window.navigator`, eg:

 - `window.navigator.fido.checkPolicy()`
 - `window.navigator.fido.discover()`

etc.

https://fidoalliance.org/specs/fido-uaf-v1.0-ps-20141208/fido-uaf-client-api-transport-v1.0-ps-20141208.html#uaf-interface

**Comment by apowers313** [comment]
Fixed with PR #1, or no?

**Comment by herrjemand** [comment]
@apowers313 No. PR patches api command interface. However currently cordova binds it to `window.fido` when it has to be at `window.navigator.fido`

**Comment by apowers313** [comment]
Oh, I see what you're saying. Actually, `var fido` ([here](https://github.com/apowers313/fido-cordova/blob/master/www/fido.js#L31)) becomes `window.fido` because `window` is the global context in the browser. Just change `var fido` to `navigator.fido` and you should have what you need.

**Comment by herrjemand** [comment]
@apowers313 yea*)

**Comment by herrjemand** [comment]
@apowers313 Somehow I thought you need some cordova magic for that XD

**Comment by apowers313** [comment]
I think cordova.exec is the only magic... :)

Let me know if you need a new build.

**Comment by herrjemand** [comment]
@apowers313 If it not too much of a hassle*)

**Comment by apowers313** [comment]
@herrjemand Let's see if I remember how to do that... ;)

**Comment by apowers313** [comment]
Try this:
[android-debug-20161103.apk.zip](https://github.com/apowers313/fido-cordova/files/570594/android-debug-20161103.apk.zip)

I don't have my debug environment running right now, so I haven't tested it.

**Comment by apowers313** [comment]
Take two:
[android-debug-20161103r1.apk.zip](https://github.com/apowers313/fido-cordova/files/570621/android-debug-20161103r1.apk.zip)

**Comment by herrjemand** [comment]
Fixing cordova polyfill now

[image: Ackermann Yuriy] <https://jeman.de/> *Ackermann Yuriy*
Developer
*e:* ackermann.yuriy@gmail.com
*g:* @herrjemand <https://github.com/herrjemand>
*w:* https://jeman.de/

2016-11-04 17:48 GMT+13:00 Adam Powers <notifications@github.com>:

**Comment by apowers313** [comment]
@herrjemand Take three:
[android-debug-20161103r2.apk.zip](https://github.com/apowers313/cordova-fido/files/570669/android-debug-20161103r2.apk.zip)

**Comment by herrjemand** [comment]
@apowers313 works like a charm

**Comment by apowers313** [comment]
thx!
